# Generated by Django 2.1.15 on 2020-12-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('cashback', models.CharField(max_length=255)),
                ('discount_percentage', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('weight', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('min_order', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
